### ISSUE TITLE
request for addition and spelling typo

### ISSUE THREAD

**Issue by kalikaneko** [tidwall/cities#5]
hi! very useful package :)
I was scratching my head trying to find "Hong Kong" in the listing, and for some reason it's missing. I'm quite positive that it deserves to be in the top 10k :)

also, minor detail, but I thought I'd mention: Colombia is spelled as "Colombi" in this listing, I don't think that matches any particular spelling.

out of curiosity, what is the source for the data?

**Comment by tidwall** [comment]
Thanks. I just fixed the dataset.
Sorry. But I don't remember exactly where the data came from.
